name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ${{ github.head_ref }}

permissions:
  checks: write
  contents: write
  statuses: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Maven build and tests
      - name: Build with Maven
        run: mvn -B test --file pom.xml

  check-format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

        # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Auto-format code if check fails
      - name: Run Spotless Check
        run: mvn clean spotless:check
        continue-on-error: true

  apply-code-formatting:
    runs-on: ubuntu-latest
    needs: check-format

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

        # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Auto-format code if check fails
      - name: Run Spotless Apply
        run: mvn clean spotless:apply

      # Step 4: Commit and push formatted code
      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply code formatting"
          git push origin ${{ github.head_ref }}
          git status
        continue-on-error: true
