name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Maven build and tests
      - name: Build with Maven
        run: mvn -B test --file pom.xml

  formatter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

        # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Spotless Check
      - name: Run Spotless Check
        run: mvn spotless:check

      # Step 4: Auto-format code if check fails
      - name: Run Spotless Apply
        if: ${{ failure() }}
        run: mvn spotless:apply

      # Step 5: Commit and push formatted code
      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' && failure() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply code formatting"
          git push
        continue-on-error: true