name: Run Junit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven


      # Step 4: Run Maven build and tests
      - name: Build with Maven
        run: mvn -B test --file pom.xml