name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  statuses: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Maven build and tests
      - name: Build with Maven
        run: mvn -B test --file pom.xml

  formatter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

        # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Auto-format code if check fails
      - name: Run Spotless Apply
        run: mvn clean spotless:apply

      # Step 4: Commit and push formatted code
      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add .
          git commit -m "Apply code formatting"
          git push origin ${{ github.head_ref }}
        continue-on-error: true

      - name: Create GitHub Check Run
        run: |
            curl -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v4+json" \
            -d '{
                  "name": "Code Formatting Check",
                  "head_sha": "${{ github.sha }}",
                  "status": "completed",
                  "conclusion": "success",
                  "output": {
                    "title": "Code formatting completed successfully",
                    "summary": "Spotless code formatting applied."
                  }
                }'