name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Run Spotless Apply
        run: mvn clean spotless:apply

      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add .
          git commit -m "Apply code formatting"
          git push origin ${{ github.head_ref }}
        continue-on-error: true

      - name: Skip subsequent workflows on bot commits
        run: |
          git log -1 --pretty=format:'%an' | grep "github-actions[bot]" && exit 0 || exit 1
        continue-on-error: true
