name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  statuses: write
  pull-requests: write

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Run Spotless Apply
        run: mvn clean spotless:apply

      - name: Commit and push changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add .
          git commit -m "Apply code formatting"
          git push origin ${{ github.head_ref }}
        continue-on-error: true

      - name: Report Status (formatter)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'formatter',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
            });

  checks:
    needs: formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B test --file pom.xml

      - name: Report Status (checks)
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'checks',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
            });
